import cs

# Used for logging or anytime the app name is needed
APP_NAME = 'ibr1700_obdII'

# MQTT Client
MQTT_CLIENT_ID = cs.CSClient().get('/config/system/system_id').get('data', '')
MQTT_LOGGING = False

# MQTT Server settings
MQTT_SERVER = '127.0.0.1'
MQTT_PORT = 1883


# OBDII MQTT Topics
VEHICLE_SPEED = 'OBDII/PIDS/VEHICLE_SPEED'
ENGINE_SPEED = 'OBDII/PIDS/ENGINE_SPEED'
THROTTLE_POSITION = 'OBDII/PIDS/THROTTLE_POSITION'
ODOMETER = 'OBDII/PIDS/ODOMETER'
FUEL_LEVEL = 'OBDII/PIDS/FUEL_LEVEL'
ENGINE_COOLANT_TEMPERATURE = 'OBDII/PIDS/ENGINE_COOLANT_TEMPERATURE'
IGNITION_STATUS = 'OBDII/PIDS/IGNITION_STATUS'
MIL_STATUS = 'OBDII/PIDS/MIL_STATUS'
FUEL_RATE = 'OBDII/PIDS/FUEL_RATE'
PTO_STATUS = 'OBDII/PIDS/PTO_STATUS'
SEATBELT_FASTENED = 'OBDII/PIDS/SEATBELT_FASTENED'
MISFIRE_MONITOR = 'OBDII/PIDS/MISFIRE_MONITOR'
FUEL_SYSTEM_MONITOR = 'OBDII/PIDS/FUEL_SYSTEM_MONITOR'
COMPREHENSIVE_COMPONENT_MONITOR = 'OBDII/PIDS/COMPREHENSIVE_COMPONENT_MONITOR'
CATALYST_MONITOR = 'OBDII/PIDS/CATALYST_MONITOR'
HEATED_CATALYST_MONITOR = 'OBDII/PIDS/HEATED_CATALYST_MONITOR'
EVAPORATIVE_SYSTEM_MONITOR = 'OBDII/PIDS/EVAPORATIVE_SYSTEM_MONITOR'
SECONDARY_AIR_SYSTEM_MONITOR = 'OBDII/PIDS/SECONDARY_AIR_SYSTEM_MONITOR'
AC_SYSTEM_REFRIGERANT_MONITOR = 'OBDII/PIDS/A\/C_SYSTEM_REFRIGERANT_MONITOR'
OXYGEN_SENSOR_MONITOR = 'OBDII/PIDS/OXYGEN_SENSOR_MONITOR'
OXYGEN_SENSOR_HEATER_MONITOR = 'OBDII/PIDS/OXYGEN_SENSOR_HEATER_MONITOR'
EGR_SYSTEM_MONITOR = 'OBDII/PIDS/EGR_SYSTEM_MONITOR'
BRAKE_SWITCH_STATUS = 'OBDII/PIDS/BRAKE_SWITCH_STATUS'
AMBIENT_AIR_TEMPERATURE = 'OBDII/PIDS/AMBIENT_AIR_TEMPERATURE'
TRIP_ODOMETER = 'OBDII/PIDS/TRIP_ODOMETER'
TRIP_FUEL_CONSUMPTION = 'OBDII/PIDS/TRIP_FUEL_CONSUMPTION'
DISTANCE_SINCE_DTC_CLEARED = 'OBDII/PIDS/DISTANCE_SINCE_DTC_CLEARED'
TRANSMISSION_FLUID_TEMPERATURE = 'OBDII/PIDS/TRANSMISSION_FLUID_TEMPERATURE'
OIL_LIFE_REMAINING = 'OBDII/PIDS/OIL_LIFE_REMAINING'
ENGINE_OIL_TEMPERATURE = 'OBDII/PIDS/ENGINE_OIL_TEMPERATURE'
BAROMETRIC_PRESSURE = 'OBDII/PIDS/BAROMETRIC_PRESSURE'
ENGINE_RUN_TIME = 'OBDII/PIDS/ENGINE_RUN_TIME'
MILES_PER_GALLON = 'OBDII/PIDS/MILES_PER_GALLON'