settings = {
    "enabled": True,
    "all_wans": False,
    "min_distance": 50,
    "enable_timer": False,
    "min_time": 0,
    "speedtests": True,
    "dead_reckoning": False,
    "packet_loss": True,
    "write_csv": True,
    "debug": False,
    "send_to_server": False,
    "full_diagnostics": False,
    "include_logs": False,
    "server_url": "https://5g-ready.io/injector",
    "server_token": "",
    "enable_surveyors": False,
    "surveyors": [],
    "speedtest_url": "www.speedtest.net/api/api.php"
}
