#!/bin/bash
# Verify all apps in apps/ have an entry in catalog.json (generated by build)
# With the new structure, we just verify package.ini files are parseable
find_errors=0

while IFS= read -r -d '' ini_file; do
    folder=$(dirname "$ini_file")
    app_name=$(basename "$folder")
    # Verify the package.ini has a section matching the folder name
    if ! grep -q "^\[$app_name\]" "$ini_file"; then
        echo "ERROR: $ini_file does not have a [$app_name] section."
        find_errors=1
    fi
done < <(find ./apps -name 'package.ini' -print0 2>/dev/null)

if [ $find_errors -eq 1 ]; then
    exit 1
fi
echo "All package.ini files are valid."
