name: Test make and package contents consistency
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run-make:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - run: |
          chmod +x ./.github/workflows/builds.sh
          ./.github/workflows/builds.sh
        shell: bash
      - run: |
          chmod +x ./.github/workflows/cslient_compare.sh
          ./.github/workflows/cslient_compare.sh 
        shell: bash
